# System Configuration
timezone: "UTC"
locale: "en_US.UTF-8"

# KVM/QEMU Configuration
kvm_group: kvm
libvirt_group: libvirt

# OPNsense Configuration
opnsense_version: "25.1"
opnsense_image_url: "https://github.com/maurice-w/opnsense-vm-images/releases/download/25.1/OPNsense-25.1-ufs-efi-vm-aarch64.qcow2.bz2"

# Docker VM Configuration
ubuntu_iso_url: "https://cdimage.ubuntu.com/releases/24.04/release/ubuntu-24.04.2-live-server-arm64.iso"

# Content Filter Configuration
content_filter_enabled: true
blocked_categories:
  - adult
  - gambling
  - malware
  - phishing

# Network Configuration (moved from inventory for consistency)
wan_interface: eth2 # Realtek 8156 (WAN)
lan_interface: eth0 # Built-in Ethernet (LAN)
bridge_interface: br0

# VM Configuration
opnsense_vm_name: opnsense-router
docker_vm_name: docker-host

# Memory allocation (in MB)
host_memory: 2048
opnsense_memory: 2048
docker_memory: 4096

# Network ranges
wan_network: "192.168.1.0/24"
lan_network: "10.0.0.0/24"
opnsense_wan_ip: "192.168.1.100"
opnsense_lan_ip: "10.0.0.1"
docker_host_ip: "10.0.0.10"
